-- MySQL Script generated by MySQL Workbench
-- 04/09/18 11:49:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coordenador` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(255) NULL,
  `Senha` VARCHAR(100) NULL,
  `Nome` VARCHAR(255) NULL,
  `Email` VARCHAR(100) NULL,
  `Celular` BIGINT(14) NULL,
  `DtExpiracao` DATE NULL DEFAULT 01/01/1900,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `Celular_UNIQUE` (`Celular` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(255) NULL,
  `Senha` VARCHAR(45) NULL,
  `Nome` VARCHAR(45) NULL,
  `Email` VARCHAR(255) NULL,
  `Celular` BIGINT(14) NULL,
  `DtExpiracao` DATE NULL DEFAULT 01/01/1900,
  `RA` BIGINT(15) NULL,
  `Foto` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `Celular_UNIQUE` (`Celular` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(255) NULL,
  `Senha` VARCHAR(100) NULL,
  `Nome` VARCHAR(255) NULL,
  `Email` VARCHAR(255) NULL,
  `Celular` BIGINT(14) NULL,
  `DtExpiracao` DATE NULL DEFAULT 01/01/1900,
  `Apelido` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `Celular_UNIQUE` (`Celular` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NULL,
  `Data` DATE NULL DEFAULT GETDATE(),
  `Status` VARCHAR(45) NULL DEFAULT 'Aberta',
  `PlanoDeEnsino` VARCHAR(45) NULL,
  `CargaHoraria` TINYINT(2) NULL DEFAULT '40','80',
  `Competencias` VARCHAR(45) NULL,
  `Habilidades` VARCHAR(45) NULL,
  `Ementa` VARCHAR(45) NULL,
  `ConteudoProgramatico` VARCHAR(45) NULL,
  `BibliografiaBasica` VARCHAR(45) NULL,
  `BibliografiaComplementar` VARCHAR(45) NULL,
  `PercentualPratico` VARCHAR(45) NULL,
  `PercentualTeorico` VARCHAR(45) NULL,
  `IdCoordenador` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC),
  UNIQUE INDEX `Status_UNIQUE` (`Status` ASC),
  INDEX `fk_Disciplina_Coordenador_idx` (`IdCoordenador` ASC),
  CONSTRAINT `fk_Disciplina_Coordenador`
    FOREIGN KEY (`IdCoordenador`)
    REFERENCES `mydb`.`Coordenador` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
