# Generated by Django 2.0.2 on 2018-05-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45, verbose_name='Login')),
                ('senha', models.CharField(max_length=30, verbose_name='Senha')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.CharField(max_length=80, verbose_name='Email')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('DtExpiração', models.DateField(default='01/01/1900', verbose_name='DtExpiração')),
                ('ra', models.IntegerField(verbose_name='RA')),
                ('foto', models.CharField(max_length=255, verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45, verbose_name='Login')),
                ('senha', models.CharField(max_length=30, verbose_name='Senha')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.CharField(max_length=80, verbose_name='Email')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('DtExpiração', models.DateField(default='01/01/1900', verbose_name='DtExpiração')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=5, verbose_name='Sigla')),
                ('etiqueta', models.SlugField(verbose_name='Etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data')),
                ('status', models.CharField(default='Aberta', max_length=50, verbose_name='Status')),
                ('PlanoEnsino', models.CharField(max_length=120, verbose_name='PlanoEnsino')),
                ('CargaHorario', models.IntegerField(verbose_name='CargaHoraria')),
                ('competencia', models.CharField(max_length=200, verbose_name='Competencias')),
                ('habilidades', models.CharField(max_length=200, verbose_name='Habilidades')),
                ('emenda', models.CharField(max_length=200, verbose_name='Emenda')),
                ('ConteudoProgramatico', models.CharField(max_length=200, verbose_name='ConteudoProgramatico')),
                ('PercentualPratico', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='PercentualPratico')),
                ('PercentualTeorico', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='PercentualTeorico')),
            ],
        ),
    ]
