-- MySQL Script generated by MySQL Workbench
-- 04/11/18 10:28:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coordenador` (
  `ID` INT NULL,
  `Login` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  `Nome` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Celular` SMALLINT(14) NULL,
  `DTexpiração` DATE NULL DEFAULT 01/01/1900,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `Celular_UNIQUE` (`Celular` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `ID` INT NULL,
  `Login` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  `Nome` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Celular` VARCHAR(45) NULL,
  `DTexpiração` VARCHAR(45) NULL,
  `RA` VARCHAR(45) NULL DEFAULT '01/01/1900',
  `Foto` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  UNIQUE INDEX `Celular_UNIQUE` (`Celular` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `ID` INT NOT NULL,
  `Login` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  `Nome` VARCHAR(45) NULL,
  `Email` VARCHAR(255) NULL,
  `Celular` SMALLINT(14) NULL,
  `DTexperação` DATE NULL DEFAULT '01/01/1900',
  `Apelido` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `Celular_UNIQUE` (`Celular` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
  `idDisciplina` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Data` DATETIME NULL DEFAULT GETDATE(),
  `Status` VARCHAR(45) NULL DEFAULT 'Aberta',
  `PlanodeEnsino` VARCHAR(45) NULL,
  `CargaHoraria` VARCHAR(45) NULL,
  `Competencias` VARCHAR(45) NULL,
  `Habilidades` VARCHAR(45) NULL,
  `Ementa` VARCHAR(45) NULL,
  `Conteudo Programatico` VARCHAR(45) NULL,
  `Bilbiografia` VARCHAR(45) NULL,
  `BibliografiaComplementar` VARCHAR(45) NULL,
  `PercentualPratico` INT NULL,
  `PercentualTeorico` INT NULL,
  `IDcordenador` INT NOT NULL,
  PRIMARY KEY (`idDisciplina`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC),
  UNIQUE INDEX `Status_UNIQUE` (`Status` ASC),
  INDEX `fk_Disciplina_Coordenador_idx` (`IDcordenador` ASC),
  CONSTRAINT `fk_Disciplina_Coordenador`
    FOREIGN KEY (`IDcordenador`)
    REFERENCES `mydb`.`Coordenador` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE Disciplina
WITH NOCHECK ADD CONSTRAINT Disciplina_CargaHoraria
CHECK (CargaHoraria in ('40','80'));


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
